// Mocks generated by Mockito 5.4.6 from annotations
// in pro_video_editor/test/pro_video_editor_method_channel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pro_video_editor/core/models/thumbnail/thumbnail_box_fit_model.dart'
    as _i10;
import 'package:pro_video_editor/core/models/thumbnail/thumbnail_format_model.dart'
    as _i9;
import 'package:pro_video_editor/core/models/video/editor_video_model.dart'
    as _i2;
import 'package:pro_video_editor/core/models/video/progress_model.dart' as _i11;
import 'package:pro_video_editor/core/platform/io/io_helper.dart' as _i6;
import 'package:pro_video_editor/pro_video_editor.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEditorVideo_0 extends _i1.SmartFake implements _i2.EditorVideo {
  _FakeEditorVideo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSize_1 extends _i1.SmartFake implements _i3.Size {
  _FakeSize_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoRenderData_3 extends _i1.SmartFake
    implements _i4.VideoRenderData {
  _FakeVideoRenderData_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditorVideo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditorVideo extends _i1.Mock implements _i2.EditorVideo {
  MockEditorVideo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasBytes =>
      (super.noSuchMethod(Invocation.getter(#hasBytes), returnValue: false)
          as bool);

  @override
  bool get hasNetworkUrl =>
      (super.noSuchMethod(Invocation.getter(#hasNetworkUrl), returnValue: false)
          as bool);

  @override
  bool get hasFile =>
      (super.noSuchMethod(Invocation.getter(#hasFile), returnValue: false)
          as bool);

  @override
  bool get hasAssetPath =>
      (super.noSuchMethod(Invocation.getter(#hasAssetPath), returnValue: false)
          as bool);

  @override
  _i2.EditorVideoType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i2.EditorVideoType.file,
          )
          as _i2.EditorVideoType);

  @override
  _i2.EditorVideoType get typePreferredFile =>
      (super.noSuchMethod(
            Invocation.getter(#typePreferredFile),
            returnValue: _i2.EditorVideoType.file,
          )
          as _i2.EditorVideoType);

  @override
  set byteArray(_i5.Uint8List? value) => super.noSuchMethod(
    Invocation.setter(#byteArray, value),
    returnValueForMissingStub: null,
  );

  @override
  set file(_i6.File? value) => super.noSuchMethod(
    Invocation.setter(#file, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i5.Uint8List> safeByteArray() =>
      (super.noSuchMethod(
            Invocation.method(#safeByteArray, []),
            returnValue: _i7.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i7.Future<_i5.Uint8List>);

  @override
  _i7.Future<String> safeFilePath() =>
      (super.noSuchMethod(
            Invocation.method(#safeFilePath, []),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#safeFilePath, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i2.EditorVideo copyWith({
    _i5.Uint8List? byteArray,
    _i6.File? file,
    String? networkUrl,
    String? assetPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #byteArray: byteArray,
              #file: file,
              #networkUrl: networkUrl,
              #assetPath: assetPath,
            }),
            returnValue: _FakeEditorVideo_0(
              this,
              Invocation.method(#copyWith, [], {
                #byteArray: byteArray,
                #file: file,
                #networkUrl: networkUrl,
                #assetPath: assetPath,
              }),
            ),
          )
          as _i2.EditorVideo);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [ThumbnailConfigs].
///
/// See the documentation for Mockito's code generation for more information.
class MockThumbnailConfigs extends _i1.Mock implements _i4.ThumbnailConfigs {
  MockThumbnailConfigs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Duration> get timestamps =>
      (super.noSuchMethod(
            Invocation.getter(#timestamps),
            returnValue: <Duration>[],
          )
          as List<Duration>);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i2.EditorVideo get video =>
      (super.noSuchMethod(
            Invocation.getter(#video),
            returnValue: _FakeEditorVideo_0(this, Invocation.getter(#video)),
          )
          as _i2.EditorVideo);

  @override
  _i3.Size get outputSize =>
      (super.noSuchMethod(
            Invocation.getter(#outputSize),
            returnValue: _FakeSize_1(this, Invocation.getter(#outputSize)),
          )
          as _i3.Size);

  @override
  int get jpegQuality =>
      (super.noSuchMethod(Invocation.getter(#jpegQuality), returnValue: 0)
          as int);

  @override
  _i9.ThumbnailFormat get outputFormat =>
      (super.noSuchMethod(
            Invocation.getter(#outputFormat),
            returnValue: _i9.ThumbnailFormat.jpeg,
          )
          as _i9.ThumbnailFormat);

  @override
  _i10.ThumbnailBoxFit get boxFit =>
      (super.noSuchMethod(
            Invocation.getter(#boxFit),
            returnValue: _i10.ThumbnailBoxFit.cover,
          )
          as _i10.ThumbnailBoxFit);

  @override
  _i7.Stream<_i11.ProgressModel> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i7.Stream<_i11.ProgressModel>.empty(),
          )
          as _i7.Stream<_i11.ProgressModel>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [KeyFramesConfigs].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyFramesConfigs extends _i1.Mock implements _i4.KeyFramesConfigs {
  MockKeyFramesConfigs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get maxOutputFrames =>
      (super.noSuchMethod(Invocation.getter(#maxOutputFrames), returnValue: 0)
          as int);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i2.EditorVideo get video =>
      (super.noSuchMethod(
            Invocation.getter(#video),
            returnValue: _FakeEditorVideo_0(this, Invocation.getter(#video)),
          )
          as _i2.EditorVideo);

  @override
  _i3.Size get outputSize =>
      (super.noSuchMethod(
            Invocation.getter(#outputSize),
            returnValue: _FakeSize_1(this, Invocation.getter(#outputSize)),
          )
          as _i3.Size);

  @override
  int get jpegQuality =>
      (super.noSuchMethod(Invocation.getter(#jpegQuality), returnValue: 0)
          as int);

  @override
  _i9.ThumbnailFormat get outputFormat =>
      (super.noSuchMethod(
            Invocation.getter(#outputFormat),
            returnValue: _i9.ThumbnailFormat.jpeg,
          )
          as _i9.ThumbnailFormat);

  @override
  _i10.ThumbnailBoxFit get boxFit =>
      (super.noSuchMethod(
            Invocation.getter(#boxFit),
            returnValue: _i10.ThumbnailBoxFit.cover,
          )
          as _i10.ThumbnailBoxFit);

  @override
  _i7.Stream<_i11.ProgressModel> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i7.Stream<_i11.ProgressModel>.empty(),
          )
          as _i7.Stream<_i11.ProgressModel>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [FrameThumbnailConfigs].
///
/// See the documentation for Mockito's code generation for more information.
class MockFrameThumbnailConfigs extends _i1.Mock
    implements _i4.FrameThumbnailConfigs {
  MockFrameThumbnailConfigs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timestamp =>
      (super.noSuchMethod(
            Invocation.getter(#timestamp),
            returnValue: _FakeDuration_2(this, Invocation.getter(#timestamp)),
          )
          as Duration);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i2.EditorVideo get video =>
      (super.noSuchMethod(
            Invocation.getter(#video),
            returnValue: _FakeEditorVideo_0(this, Invocation.getter(#video)),
          )
          as _i2.EditorVideo);

  @override
  _i3.Size get outputSize =>
      (super.noSuchMethod(
            Invocation.getter(#outputSize),
            returnValue: _FakeSize_1(this, Invocation.getter(#outputSize)),
          )
          as _i3.Size);

  @override
  int get jpegQuality =>
      (super.noSuchMethod(Invocation.getter(#jpegQuality), returnValue: 0)
          as int);

  @override
  _i9.ThumbnailFormat get outputFormat =>
      (super.noSuchMethod(
            Invocation.getter(#outputFormat),
            returnValue: _i9.ThumbnailFormat.jpeg,
          )
          as _i9.ThumbnailFormat);

  @override
  _i10.ThumbnailBoxFit get boxFit =>
      (super.noSuchMethod(
            Invocation.getter(#boxFit),
            returnValue: _i10.ThumbnailBoxFit.cover,
          )
          as _i10.ThumbnailBoxFit);

  @override
  _i7.Stream<_i11.ProgressModel> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i7.Stream<_i11.ProgressModel>.empty(),
          )
          as _i7.Stream<_i11.ProgressModel>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [VideoRenderData].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoRenderData extends _i1.Mock implements _i4.VideoRenderData {
  MockVideoRenderData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i4.VideoOutputFormat get outputFormat =>
      (super.noSuchMethod(
            Invocation.getter(#outputFormat),
            returnValue: _i4.VideoOutputFormat.mp4,
          )
          as _i4.VideoOutputFormat);

  @override
  bool get enableAudio =>
      (super.noSuchMethod(Invocation.getter(#enableAudio), returnValue: false)
          as bool);

  @override
  List<List<double>> get colorMatrixList =>
      (super.noSuchMethod(
            Invocation.getter(#colorMatrixList),
            returnValue: <List<double>>[],
          )
          as List<List<double>>);

  @override
  List<_i4.ColorFilter> get colorFilters =>
      (super.noSuchMethod(
            Invocation.getter(#colorFilters),
            returnValue: <_i4.ColorFilter>[],
          )
          as List<_i4.ColorFilter>);

  @override
  List<_i4.BlurFilter> get blurFilters =>
      (super.noSuchMethod(
            Invocation.getter(#blurFilters),
            returnValue: <_i4.BlurFilter>[],
          )
          as List<_i4.BlurFilter>);

  @override
  List<_i4.VideoAudioTrack> get audioTracks =>
      (super.noSuchMethod(
            Invocation.getter(#audioTracks),
            returnValue: <_i4.VideoAudioTrack>[],
          )
          as List<_i4.VideoAudioTrack>);

  @override
  bool get shouldOptimizeForNetworkUse =>
      (super.noSuchMethod(
            Invocation.getter(#shouldOptimizeForNetworkUse),
            returnValue: false,
          )
          as bool);

  @override
  bool get imageBytesWithCropping =>
      (super.noSuchMethod(
            Invocation.getter(#imageBytesWithCropping),
            returnValue: false,
          )
          as bool);

  @override
  bool get loopCustomAudio =>
      (super.noSuchMethod(
            Invocation.getter(#loopCustomAudio),
            returnValue: false,
          )
          as bool);

  @override
  List<_i4.PixelateFilter> get pixelateFilters =>
      (super.noSuchMethod(
            Invocation.getter(#pixelateFilters),
            returnValue: <_i4.PixelateFilter>[],
          )
          as List<_i4.PixelateFilter>);

  @override
  _i4.EncoderPreference get encoderPreference =>
      (super.noSuchMethod(
            Invocation.getter(#encoderPreference),
            returnValue: _i4.EncoderPreference.auto,
          )
          as _i4.EncoderPreference);

  @override
  _i7.Stream<_i11.ProgressModel> get progressStream =>
      (super.noSuchMethod(
            Invocation.getter(#progressStream),
            returnValue: _i7.Stream<_i11.ProgressModel>.empty(),
          )
          as _i7.Stream<_i11.ProgressModel>);

  @override
  _i7.Future<Map<String, dynamic>> toAsyncMap() =>
      (super.noSuchMethod(
            Invocation.method(#toAsyncMap, []),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i4.VideoRenderData copyWith({
    String? id,
    _i4.VideoQualityConfig? qualityConfig,
    _i4.VideoOutputFormat? outputFormat,
    _i2.EditorVideo? video,
    List<_i4.VideoSegment>? videoSegments,
    _i5.Uint8List? imageBytes,
    List<_i4.ImageLayer>? imageLayers,
    _i4.ExportTransform? transform,
    bool? enableAudio,
    double? playbackSpeed,
    Duration? startTime,
    Duration? endTime,
    List<List<double>>? colorMatrixList,
    List<_i4.ColorFilter>? colorFilters,
    List<_i4.BlurFilter>? blurFilters,
    List<_i4.VideoAudioTrack>? audioTracks,
    double? blur,
    int? bitrate,
    String? customAudioPath,
    Duration? customAudioStartTime,
    double? originalAudioVolume,
    double? customAudioVolume,
    bool? shouldOptimizeForNetworkUse,
    bool? imageBytesWithCropping,
    bool? loopCustomAudio,
    List<_i4.PixelateFilter>? pixelateFilters,
    int? fps,
    _i4.VideoCodec? codec,
    _i4.EncoderPreference? encoderPreference,
    _i4.VideoAdjustment? adjustment,
    _i4.VignetteFilter? vignetteFilter,
    List<_i4.TextLayer>? textLayers,
    List<_i4.ShapeLayer>? shapeLayers,
    List<_i4.StickerLayer>? stickerLayers,
    List<_i4.VideoOverlayLayer>? videoOverlayLayers,
    _i4.BackgroundCanvas? backgroundCanvas,
    _i4.VideoResolutionPreset? resolutionPreset,
    _i4.AudioCrossfade? audioCrossfade,
    int? originalAudioTrackIndex,
    String? replaceOriginalAudioPath,
    _i4.LoudnessNormalization? loudnessNormalization,
    _i4.AudioDucking? audioDucking,
    _i4.AudioPan? audioPan,
    _i4.VoiceOverRecordingConfig? voiceOverRecordingConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #qualityConfig: qualityConfig,
              #outputFormat: outputFormat,
              #video: video,
              #videoSegments: videoSegments,
              #imageBytes: imageBytes,
              #imageLayers: imageLayers,
              #transform: transform,
              #enableAudio: enableAudio,
              #playbackSpeed: playbackSpeed,
              #startTime: startTime,
              #endTime: endTime,
              #colorMatrixList: colorMatrixList,
              #colorFilters: colorFilters,
              #blurFilters: blurFilters,
              #audioTracks: audioTracks,
              #blur: blur,
              #bitrate: bitrate,
              #customAudioPath: customAudioPath,
              #customAudioStartTime: customAudioStartTime,
              #originalAudioVolume: originalAudioVolume,
              #customAudioVolume: customAudioVolume,
              #shouldOptimizeForNetworkUse: shouldOptimizeForNetworkUse,
              #imageBytesWithCropping: imageBytesWithCropping,
              #loopCustomAudio: loopCustomAudio,
              #pixelateFilters: pixelateFilters,
              #fps: fps,
              #codec: codec,
              #encoderPreference: encoderPreference,
              #adjustment: adjustment,
              #vignetteFilter: vignetteFilter,
              #textLayers: textLayers,
              #shapeLayers: shapeLayers,
              #stickerLayers: stickerLayers,
              #videoOverlayLayers: videoOverlayLayers,
              #backgroundCanvas: backgroundCanvas,
              #resolutionPreset: resolutionPreset,
              #audioCrossfade: audioCrossfade,
              #originalAudioTrackIndex: originalAudioTrackIndex,
              #replaceOriginalAudioPath: replaceOriginalAudioPath,
              #loudnessNormalization: loudnessNormalization,
              #audioDucking: audioDucking,
              #audioPan: audioPan,
              #voiceOverRecordingConfig: voiceOverRecordingConfig,
            }),
            returnValue: _FakeVideoRenderData_3(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #qualityConfig: qualityConfig,
                #outputFormat: outputFormat,
                #video: video,
                #videoSegments: videoSegments,
                #imageBytes: imageBytes,
                #imageLayers: imageLayers,
                #transform: transform,
                #enableAudio: enableAudio,
                #playbackSpeed: playbackSpeed,
                #startTime: startTime,
                #endTime: endTime,
                #colorMatrixList: colorMatrixList,
                #colorFilters: colorFilters,
                #blurFilters: blurFilters,
                #audioTracks: audioTracks,
                #blur: blur,
                #bitrate: bitrate,
                #customAudioPath: customAudioPath,
                #customAudioStartTime: customAudioStartTime,
                #originalAudioVolume: originalAudioVolume,
                #customAudioVolume: customAudioVolume,
                #shouldOptimizeForNetworkUse: shouldOptimizeForNetworkUse,
                #imageBytesWithCropping: imageBytesWithCropping,
                #loopCustomAudio: loopCustomAudio,
                #pixelateFilters: pixelateFilters,
                #fps: fps,
                #codec: codec,
                #encoderPreference: encoderPreference,
                #adjustment: adjustment,
                #vignetteFilter: vignetteFilter,
                #textLayers: textLayers,
                #shapeLayers: shapeLayers,
                #stickerLayers: stickerLayers,
                #videoOverlayLayers: videoOverlayLayers,
                #backgroundCanvas: backgroundCanvas,
                #resolutionPreset: resolutionPreset,
                #audioCrossfade: audioCrossfade,
                #originalAudioTrackIndex: originalAudioTrackIndex,
                #replaceOriginalAudioPath: replaceOriginalAudioPath,
                #loudnessNormalization: loudnessNormalization,
                #audioDucking: audioDucking,
                #audioPan: audioPan,
                #voiceOverRecordingConfig: voiceOverRecordingConfig,
              }),
            ),
          )
          as _i4.VideoRenderData);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#toJson, []),
            ),
          )
          as String);
}
